export const SET_LATEST_ANIME = "SET_LATEST_ANIME";
export const SET_VIDEO_ANIME = "SET_VIDEO_ANIME";
export const SET_ANIME_LETTER = "SET_ANIME_LETTER";
export const SET_ANIME_SEARCH = "SET_ANIME_SEARCH";
export const SET_ANIME_GENRES = "SET_ANIME_GENRES";
export const SET_MOVIES = "SET_MOVIES";
export const SET_OVAS = "SET_OVAS";
export const IS_LOADING = "IS_LOADING";